config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'welcome/index', to: 'welcome#index', as: 'welcome_index'
  root 'welcome#index'

  get 'publications/search', to: 'publications#search', as: 'publications_search', format: :html
  # para cuando este listo
  # root :to 'publications#index'
  # resources :publications (?)

  ############################################################################

  # CREATE
  get 'publications/new', to: 'publications#new', as: 'publications_new'
  post 'publications', to: 'publications#create'

  get 'reviews/new', to: 'reviews#new', as: 'reviews_new'
  post 'reviews', to: 'reviews#create'

  get 'chats/new', to: 'chats#new', as: 'chats_new'
  post 'chats', to: 'chats#create'

  get 'comments/new', to: 'comments#new', as: 'comments_new'
  post 'comments', to: 'comments#create'

  get 'requests/new', to: 'requests#new', as: 'requests_new'
  post 'requests', to: 'requests#create'

  get 'messages/new', to: 'messages#new', as: 'messages_new'
  post 'messages', to: 'messages#create'
  ############################################################################

  # READ
  get 'publications/index', to: 'publications#index', as: 'publications_index'
  get 'publications/:id', to: 'publications#show', as: 'publications_show'

  get 'reviews/index', to: 'reviews#index', as: 'reviews_index'
  get 'reviews/:id', to: 'reviews#show', as: 'reviews_show'

  get 'chats/index', to: 'chats#index', as: 'chats_index'
  get 'chats/:id', to: 'chats#show', as: 'chats_show'

  get 'comments/index', to: 'comments#index', as: 'comments_index'
  get 'comments/:id', to: 'comments#show', as: 'comments_show'

  get 'requests/index', to: 'requests#index', as: 'requests_index'
  get 'requests/:id', to: 'requests#show', as: 'requests_show'

  get 'messages/index', to: 'messages#index', as: 'messages_index'
  get 'messages/:id', to: 'messages#show', as: 'messages_show'

  # get 'users/:id', to: 'users#show', as: 'users_show'

  ############################################################################

  # UPDATE
  get 'publications/:id/edit', to: 'publications#edit', as: 'publications_edit'
  patch 'publications/:id', to: 'publications#update', as: 'publications_update'

  get 'reviews/:id/edit', to: 'reviews#edit', as: 'reviews_edit'
  patch 'reviews/:id', to: 'reviews#update', as: 'reviews_update'

  get 'chats/:id/edit', to: 'chats#edit', as: 'chats_edit'
  patch 'chats/:id', to: 'chats#update', as: 'chats_update'

  get 'comments/:id/edit', to: 'comments#edit', as: 'comments_edit'
  patch 'comments/:id', to: 'comments#update', as: 'comments_update'

  get 'requests/:id/edit', to: 'requests#edit', as: 'requests_edit'
  patch 'requests/:id', to: 'requests#update', as: 'requests_update'

  get 'messages/:id/edit', to: 'messages#edit', as: 'messages_edit'
  patch 'messages/:id', to: 'messages#update', as: 'messages_update'

  ############################################################################

  # DELETE
  delete 'publications/:id', to: 'publications#delete', as: 'publications_delete'

  delete 'reviews/:id', to: 'reviews#delete', as: 'reviews_delete'

  delete 'chats/:id', to: 'chats#delete', as: 'chats_delete'

  delete 'comments/:id', to: 'comments#delete', as: 'comments_delete'

  delete 'requests/:id', to: 'requests#delete', as: 'requests_delete'

  delete 'messages/:id', to: 'messages#delete', as: 'messages_delete'
  ############################################################################

  # DEVISE
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' },
                     path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :users, only: [:show]
  delete 'users/:id', to: 'users#destroy', as: 'admin_destroy_user'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  validates :publication_id, :user_id, :description, presence: { message: 'Debes completas todas las casillas' }
  validates :publication_id, :user_id, numericality: { only_integer: { message: 'El valor debe ser numérico' } }

  belongs_to :publication
  belongs_to :user
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]
  def new
    @comment = Comment.new
  end

  def create
    @comments_params = params.require(:comment).permit(:publication_id, :user_id, :description)
    @comment = Comment.create(@comments_params)
    if @comment.save
      redirect_to publications_show_path(@comments_params['publication_id'].to_i),
                  notice: 'Comentario creado correctamente'
    else
      render :new
    end
  end

  def index
    @comments = Comment.all
  end

  def show
    @comment = Comment.find_by(id: params[:id])
  end

  def edit
    @comment = Comment.find_by(id: params[:id])
  end

  def update
    @comment = Comment.find_by(id: params[:id])
    @comments_params = params.require(:comment).permit(:publication_id, :user_id, :description)
    if @comment.update(@comments_params)
      redirect_to publications_show_path(@comment.publication_id),
                  notice: 'El comentario ha sido editado correctamente'
    else
      render :edit
    end
  end

  def delete
    @comment = Comment.find_by(id: params[:id])
    id_p = @comment.publication_id.to_i
    @comment.destroy
    redirect_to publications_show_path(id_p)
  end
end

app/helpers/comments_helper.rb
# frozen_string_literal: true

module CommentsHelper
end

app/views/comments/edit.html.erb
<br>
<h1 class='is-size-2' style="margin-left: 20px">Editar comentario</h1>
<br>
<br>

<div style="margin-left:20px">
<%= form_with(model: @comment, method: :patch, url: comments_update_path, local: true) do |form| %>
    <%- if @comment.errors.any? %>
        <div class="notification is-danger" style="width: 30%">
            Algo ha salido mal!
        </div>
    <% end %>
    <div class="field">
        <label class="label is-size-4 has-text-weight-light">Comentario</label>
        <div class="control" style="padding-right: 70%">
            <%= form.text_field :description, class: "input" %>
        </div>
    </div>
    <%- if @comment.errors[:description].any?%>
    <div class= "help is-danger">
        <%= @comment.errors[:description].first %>
    </div>
    <% end %>
    <br>
    <div class="control">
        <div class="action">
            <%= form.submit "Guardar Comentario", class: "button is-link" %>
        </div>
    </div>
<% end %>
</div>

<button class="button is-rounded" style="margin-top: 20px; margin-left: 20px"><%= link_to 'Volver', publications_show_path(@comment.publication_id) %></button>

app/views/comments/index.html.erb
<br>
<h1 style="margin-left: 20px" class='is-size-2'>Comentarios</h1>

<% if notice %>
    <div class="notification is-success" style= "width:30%; margin-left: 1%;text-align: center;">
        <%= notice %>
    </div>
<% end %>

<div class="container">
    <table class="table">
        <thead>
            <tr>
                <th>Publicación</th>
                <th>Usuario</th>
                <th>Comentario</th>
                <th colspan="3">Acciones</th>
            </tr>
        </thead>

        <tbody>
            <% @comments.each do |comment| %>
                <tr>
                    <td><%= comment.publication_id %></td>
                    <td><%= comment.user_id %></td>
                    <td><%= comment.description %></td>
                    <td><%= link_to 'Ver detalle', comments_show_path(comment.id)%></td>
                </tr>
            <% end %>
        </tbody>
    </table>
</div>

<button class="button is-rounded" style="margin-top: 20px; margin-left: 20px"><%= link_to 'Crear nuevo comentario', comments_new_path %></button>

app/views/comments/new.html.erb
<br>
<h1 class='is-size-2' style="margin-left: 20px">Nuevo comentario</h1>
<br>
<br>
<div style="margin-left:20px">
<%= form_with(model: @comment, method: :post, local: true) do |form| %>
    <%- if @comment.errors.any? %>
        <div class="notification is-danger" style="width: 30%">
            Algo ha salido mal!
        </div>
    <% end %>
    <div class="field">
        <div class="control" style="padding-right: 70%">
            <%= form.text_field :publication_id, class: "input", value: params[:id_pb].to_i, type: :hidden %>
        </div>
    </div>
        <div class="field">
        <div class="control" style="padding-right: 70%">
            <%= form.text_field :user_id, class: "input" , value: current_user.id, type: :hidden %>
        </div>
    </div>
    <div class="field">
        <label class="label is-size-4 has-text-weight-light">Comentario</label>
        <div class="control" style="padding-right: 70%">
            <%= form.text_field :description, class: "input" %>
        </div>
    </div>
    <%- if @comment.errors[:description].any?%>
    <div class= "help is-danger">
        <%= @comment.errors[:description].first %>
    </div>
    <% end %>
    <br>
    <div class="control">
        <div class="action">
            <%= form.submit "Crear Comentario", class: "button is-link" %>
        </div>
    </div>
<% end %>
</div>
<button class="button is-rounded" style="margin-top: 20px; margin-left: 20px"><%= link_to 'Volver', publications_show_path(params[:id_pb].to_i) %></button>

app/views/comments/show.html.erb
<p style="margin-top: 20px; margin-left: 20px;"><%= notice %></p>

<table class="table is-striped">
    <thead>
        <tr>
            <th>Publicación</th>
            <th>Usuario</th>
            <th>Comentario</th>
        </tr>
    </thead>

    <tbody>
        <tr>
            <td><%= @comment.publication_id if @comment %></td>
            <td><%= @comment.user_id if @comment %></td>
            <td><%= @comment.description  if @comment%></td>
        </tr>
    </tbody>
</table>

<button class="button is-rounded" style="margin-top: 20px; margin-left: 20px; margin-bottom: 30px"><%= link_to 'Volver', comments_index_path %></button>
<button class="button is-rounded" style="margin-top: 20px; margin-left: 20px; margin-bottom: 30px"><%= link_to 'Editar', comments_edit_path(@comment.id) if @comment %></button>
<button class="button is-rounded" style="margin-top: 20px; margin-left: 20px; margin-bottom: 30px"><%= link_to 'Eliminar', comments_delete_path(@comment.id), method: :delete if @comment %></button>