config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'welcome/index', to: 'welcome#index', as: 'welcome_index'
  root 'welcome#index'

  get 'publications/search', to: 'publications#search', as: 'publications_search', format: :html
  # para cuando este listo
  # root :to 'publications#index'
  # resources :publications (?)

  ############################################################################

  # CREATE
  get 'publications/new', to: 'publications#new', as: 'publications_new'
  post 'publications', to: 'publications#create'

  get 'reviews/new', to: 'reviews#new', as: 'reviews_new'
  post 'reviews', to: 'reviews#create'

  get 'chats/new', to: 'chats#new', as: 'chats_new'
  post 'chats', to: 'chats#create'

  get 'comments/new', to: 'comments#new', as: 'comments_new'
  post 'comments', to: 'comments#create'

  get 'requests/new', to: 'requests#new', as: 'requests_new'
  post 'requests', to: 'requests#create'

  get 'messages/new', to: 'messages#new', as: 'messages_new'
  post 'messages', to: 'messages#create'
  ############################################################################

  # READ
  get 'publications/index', to: 'publications#index', as: 'publications_index'
  get 'publications/:id', to: 'publications#show', as: 'publications_show'

  get 'reviews/index', to: 'reviews#index', as: 'reviews_index'
  get 'reviews/:id', to: 'reviews#show', as: 'reviews_show'

  get 'chats/index', to: 'chats#index', as: 'chats_index'
  get 'chats/:id', to: 'chats#show', as: 'chats_show'

  get 'comments/index', to: 'comments#index', as: 'comments_index'
  get 'comments/:id', to: 'comments#show', as: 'comments_show'

  get 'requests/index', to: 'requests#index', as: 'requests_index'
  get 'requests/:id', to: 'requests#show', as: 'requests_show'

  get 'messages/index', to: 'messages#index', as: 'messages_index'
  get 'messages/:id', to: 'messages#show', as: 'messages_show'

  # get 'users/:id', to: 'users#show', as: 'users_show'

  ############################################################################

  # UPDATE
  get 'publications/:id/edit', to: 'publications#edit', as: 'publications_edit'
  patch 'publications/:id', to: 'publications#update', as: 'publications_update'

  get 'reviews/:id/edit', to: 'reviews#edit', as: 'reviews_edit'
  patch 'reviews/:id', to: 'reviews#update', as: 'reviews_update'

  get 'chats/:id/edit', to: 'chats#edit', as: 'chats_edit'
  patch 'chats/:id', to: 'chats#update', as: 'chats_update'

  get 'comments/:id/edit', to: 'comments#edit', as: 'comments_edit'
  patch 'comments/:id', to: 'comments#update', as: 'comments_update'

  get 'requests/:id/edit', to: 'requests#edit', as: 'requests_edit'
  patch 'requests/:id', to: 'requests#update', as: 'requests_update'

  get 'messages/:id/edit', to: 'messages#edit', as: 'messages_edit'
  patch 'messages/:id', to: 'messages#update', as: 'messages_update'

  ############################################################################

  # DELETE
  delete 'publications/:id', to: 'publications#delete', as: 'publications_delete'

  delete 'reviews/:id', to: 'reviews#delete', as: 'reviews_delete'

  delete 'chats/:id', to: 'chats#delete', as: 'chats_delete'

  delete 'comments/:id', to: 'comments#delete', as: 'comments_delete'

  delete 'requests/:id', to: 'requests#delete', as: 'requests_delete'

  delete 'messages/:id', to: 'messages#delete', as: 'messages_delete'
  ############################################################################

  # DEVISE
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' },
                     path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :users, only: [:show]
  delete 'users/:id', to: 'users#destroy', as: 'admin_destroy_user'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/publication.rb
# frozen_string_literal: true

class Publication < ApplicationRecord
  validates :user_id, :title, :kind, :direction, :species, :image,
            presence: { message: 'Debes completar todas las casillas requeridas' }
  validates :user_id, numericality: { only_integer: true, message: 'El valor debe ser numérico' }
  validates :price, numericality: { only_integer: true, message: 'El valor debe ser numérico' }

  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :commenters, through: :comments, class_name: 'User'
  has_many :requests, dependent: :destroy

  has_one_attached :image
end

app/controllers/publications_controller.rb
# frozen_string_literal: true

class PublicationsController < ApplicationController
  before_action :authenticate_user!, except: %i[index show search]
  def index
    @publications = Publication.all
  end

  def show
    @publication = Publication.find_by(id: params[:id])
    @user_name = User.find_by(id: @publication.user_id).name
    @comments = Comment.all
    @users = User.all
  end

  def new
    @publication = Publication.new
  end

  def create
    @publications_params = params.require(:publication).permit(:user_id, :title, :kind, :price,
                                                               :direction, :species, :image)
    @publication = Publication.create(@publications_params)
    if @publication.save
      redirect_to publications_index_path, notice: 'Publicacion creada correctamente'
    else
      render :new
    end
  end

  respond_to :html
  def search
    query = params[:search]
    results = Publication.where('title LIKE ?', "%#{query}%")

    if params[:filter] == 'Selecciona una opción'
      @publications = results
    else
      symbol = params[:filter]
      @publications = results.where(kind: symbol)
    end
  end

  def edit
    @publication = Publication.find_by(id: params[:id])
  end

  def update
    @publication = Publication.find_by(id: params[:id])
    @publications_params = params.require(:publication).permit(:user_id, :title, :kind, :price,
                                                               :direction, :species, :image)

    if @publication.update(@publications_params)
      redirect_to publications_index_path, notice: 'Publicacion editada correctamente'
    else
      render :edit
    end
  end

  def delete
    @publication = Publication.find_by(id: params[:id])
    if (@publication.user_id == current_user.id) | (current_user.admin_role)
      @publication.destroy
      redirect_to publications_index_path, notice: 'La publicacion ha sido eliminada'
    end
  end
end

app/helpers/publications_helper.rb
# frozen_string_literal: true

module PublicationsHelper
end

app/views/publications/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/publications/edit.html.erb
<br>
<h1 class='is-size-2' style="margin-left:20px">Editar Publicacion</h1>
<br>
<br>
<div style="margin-left:20px">
<%= form_with(model: @publication, method: :patch, url: publications_update_path, local: true) do |form| %>
    <%- if @publication.errors.any? %>
        <div class="notification is-danger" style="width: 30%">
            Algo ha salido mal!
        </div>
    <% end %>
        <div class="field">
            <label class="label is-size-4 has-text-weight-light">Título</label>
            <div class="control" style="padding-right: 70%">
                <%= form.text_field :title, class: "input" %>
            </div>
        </div>
        <%- if @publication.errors[:title].any?%>
            <div class= "help is-danger">
                <%= @publication.errors[:title].first %>
            </div>
        <% end %>
    <br>
        <div class="field">
        <label class="label is-size-4 has-text-weight-light">Tipo de publicación</label>
            <div class="control" style="padding-right: 70%">
                <div class="select">
                    <%= form.select(:kind, options_for_select([["Adopción", "Adopción"],["Venta", "Venta"]])) %>
                </div>
            </div>
        </div>
        <%- if @publication.errors[:kind].any?%>
            <div class= "help is-danger">
                <%= @publication.errors[:kind].first %>
            </div>
        <% end %>
    <br>
        <div class="field">
            <label class="label is-size-4 has-text-weight-light">Precio</label>
            <div class="control" style="padding-right: 70%">
                <%= form.text_field :price, class: "input" %>
            </div>
        </div>
        <%- if @publication.errors[:price].any?%>
            <div class= "help is-danger">
                <%= @publication.errors[:price].first %>
            </div>
        <% end %>
    <br>
        <div class="field">
            <label class="label is-size-4 has-text-weight-light">Dirección</label>
            <div class="control" style="padding-right: 70%">
                <%= form.text_field :direction, class: "input" %>
            </div>
        </div>
        <%- if @publication.errors[:direction].any?%>
            <div class= "help is-danger">
                <%= @publication.errors[:direction].first %>
            </div>
        <% end %>
    <br>
        <div class="field">
            <label class="label is-size-4 has-text-weight-light">Especie</label>
            <div class="control" style="padding-right: 70%">
                <%= form.text_field :species, class: "input" %>
            </div>
        </div>
        <%- if @publication.errors[:species].any?%>
            <div class= "help is-danger">
                <%= @publication.errors[:species].first %>
            </div>
        <% end %>
    <br>

    <div class="control">
        <div class="action">
            <%= form.submit "Guardar", class: "button is-link" %>
        </div>
    </div>
<% end %>
</div>

<button class="button is-rounded" style="margin-top: 20px; margin-left: 20px; margin-bottom: 30px"><%= link_to 'Volver',publications_show_path(@publication.id) if @publication %></button>
<button class="button is-rounded" style="margin-top: 20px; margin-left: 20px; margin-bottom: 30px"><%= link_to 'Otras publicaciones', publications_index_path %></button>

app/views/publications/index.html.erb
<br>
<h1 style="margin-left: 20px" class='is-size-2'>Publicaciones</h1>

<% if notice %>
    <div class="notification is-success" style= "width:30%; text-align: center;">
        <%= notice %>
    </div>
<% end %>

<div style="margin-bottom: 30px">
<%= form_tag(publications_search_path, method: :get) do %>
  <%= text_field_tag :search, '', class: 'input is-primary is-two-fifths', placeholder: "Busqueda por título", style: 'margin-left: 20px; width: 30%'%>
  <div class="select">
  <%= select_tag :filter, options_for_select(['Selecciona una opción', 'Venta','Adopción']), class: "custom-select" %>
  </div>
  <%= submit_tag 'Buscar', class: "button is-light" %>
<% end %>
</div>

<% @publications.each do |pub| %>
    <div style="margin-left: 1%; margin-right: 1%;border-color: black;border-style: solid;border-radius: 7px;; margin-bottom: 1%; width: 50%">
        <div class="card">
            <header class="card-header" style="display:block;padding-top: 1%; background-color: lightblue">
                <p class="title" style="margin-left: 1%">
                    <strong> <%= User.find_by(id: pub.user_id).name %> </strong>
                </p>
                <p class="subtitle" style="margin-left: 1%; padding-bottom: 1%">
                    <i> "<%= pub.title  %>" </i>
                </p>
            </header>
        </div>

        <div class="columns">
            <div class="column is-two-third">
                <div class="card-content" style="">
                    <div class="content">
                        <div class="table-container" style="padding-right:20%;margin:center;">
                            <table class="table is-hoverable">
                                <tr>
                                    <th> Venta/Adopcion: </th>
                                    <td> <%= pub.kind %> </td>
                                </tr>
                                <tr>
                                    <th> Especie: </th>
                                    <td> <%= pub.species %> </td>
                                </tr>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
            <div class="column">
                <div class="card-content">
                    <figure class="image">
                        <%= image_tag(pub.image) %>
                    </figure>
                </div>
            </div>
        </div>
        <br>
        <footer class="card-footer" style="padding-top:1%; margin-bottom: 1%">
            <a style="margin-left:1%"> <%= link_to 'Ver detalle', publications_show_path(pub.id) %> </a>
        </footer>
    </div>
<% end %>

<% if current_user %>
    <button class="button is-rounded" style="margin-top: 20px; margin-left: 20px"><%= link_to 'Crear nueva publicación', publications_new_path %></button>
<% end %>

app/views/publications/new.html.erb
<br>
<h1 class='is-size-2' style="margin-left:20px">Crear Nueva Publicacion</h1>
<br>
<br>
<div style="margin-left:20px">
<%= form_with(model: @publication, method: :post, local: true) do |form| %>
    <%- if @publication.errors.any? %>
        <div class="notification is-danger" style="width: 30%">
            Algo ha salido mal!
        </div>
    <% end %>
    <div class="control" style="padding-right: 70%">
    <%= form.text_field :user_id, class: "input", value: current_user.id, type: :hidden %>
    </div>
    <div class="field">
        <label class="label is-size-4 has-text-weight-light">Título</label>
        <div class="control" style="padding-right: 70%">
            <%= form.text_field :title, class: "input" %>
        </div>
        <%- if @publication.errors[:title].any?%>
            <div class= "help is-danger">
                <%= @publication.errors[:title].first %>
            </div>
        <% end %>
    </div>
    <br>
        <div class="field">
        <label class="label is-size-4 has-text-weight-light">Tipo de publicación</label>
        <div class="control" style="padding-right: 70%">
            <div class="select">
                <%= form.select(:kind, options_for_select([["Adopción", "Adopción"],["Venta", "Venta"]])) %>
            </div>
        </div>
        <%- if @publication.errors[:kind].any?%>
            <div class= "help is-danger">
                <%= @publication.errors[:kind].first %>
            </div>
        <% end %>
    </div>
    <br>
        <div class="field">
        <label class="label is-size-4 has-text-weight-light">Precio</label>
        <div class="control" style="padding-right: 70%">
            <%= form.text_field :price, class: "input" %>
        </div>
        <%- if @publication.errors[:price].any?%>
            <div class= "help is-danger">
                <%= @publication.errors[:price].first %>
            </div>
        <% end %>
    </div>
    <br>
        <div class="field">
        <label class="label is-size-4 has-text-weight-light">Dirección</label>
        <div class="control" style="padding-right: 70%">
            <%= form.text_field :direction, class: "input" %>
        </div>
        <%- if @publication.errors[:direction].any?%>
            <div class= "help is-danger">
            <%= @publication.errors[:direction].first %>
            </div>
        <% end %>
    </div>
    <br>
        <div class="field">
        <label class="label is-size-4 has-text-weight-light">Especie</label>
        <div class="control" style="padding-right: 70%">
            <%= form.text_field :species, class: "input" %>
        </div>
        <%- if @publication.errors[:species].any?%>
            <div class= "help is-danger">
            <%= @publication.errors[:species].first %>
            </div>
        <% end %>
    </div>
    <br>
        <div class="field">
        <label class="label is-size-4 has-text-weight-light">Foto</label>
        <div class="control" style="padding-right: 70%">
            <%= form.file_field :image, class: "input" %>
        </div>
        <%- if @publication.errors[:image].any?%>
            <div class= "help is-danger">
            <%= @publication.errors[:image].first %>
            </div>
        <% end %>
    </div>   
    <br>
 

    <div class="control">
        <div class="action">
            <%= form.submit "Crear Publicación", class: "button is-link" %>
        </div>
    </div>
<% end %>
</div>

<button class="button is-rounded" style="margin-top: 20px; margin-left: 20px; margin-bottom: 30px"><%= link_to 'Volver a la lista de publicaciones', publications_index_path %></button>

app/views/publications/search.html.erb
<div class="container" id='publications-container'>
    <table class="table">
        <thead>
            <tr>
                <th>Usuario</th>
                <th>Titulo</th>
                <th>Tipo</th>
                <th>Especie</th>
                <th>Imagen</th>
                <th colspan='3'>Acciones</th>
            </tr>
        </thead>

        <tbody>
            <% @publications.each do |pub| %>
                <tr>
                    <td><%= User.find_by(id: pub.user_id).name %></td>
                    <td><%= pub.title %></td>
                    <td><%= pub.kind %></td>
                    <td><%= pub.species %></td>
                    <td><%= image_tag(pub.image) %></td>
                    <td><%= link_to 'Ver detalle', publications_show_path(pub.id) %></td>
                </tr>
            <% end %>
        </tbody>
    </table>
</div>

<button class="button is-rounded" style="margin-top: 20px; margin-left: 20px"><%= link_to 'Crear nueva publicación', publications_new_path %></button>
<br>
<br>
<br>

app/views/publications/show.html.erb
<% if notice %>
    <div class="notification is-success" style= "width:30%; text-align: center;margin-left: 20px; margin-top: 1%">
        <%= notice %>
    </div>
<% end %>

<div style="margin-left: 1%; margin-right: 1%;border-color: black;border-style: solid;border-radius: 7px;; margin-bottom: 1%; width: 50%; margin-top: 1%">
    <div class="card">
        <header class="card-header" style="display:block;padding-top: 1%; background-color: lightblue">
            <p class="title" style="margin-left: 1%">
                <strong> <%= User.find_by(id: @publication.user_id).name if @publication %> </strong>
            </p>
            <p class="subtitle" style="margin-left: 1%; padding-bottom: 1%">
                <i> "<%= @publication.title if @publication  %>" </i>
            </p>
        </header>
    </div>

    <div class="columns">
        <div class="column is-two-third">
            <div class="card-content" style="">
                <div class="content">
                    <div class="table-container" style="padding-right:20%;margin:center;">
                        <table class="table is-hoverable">
                            <tr>
                                <th> Venta/Adopcion: </th>
                                <td> <%= @publication.kind if @publication %> </td>
                            </tr>
                            <tr>
                                <th> Especie: </th>
                                <td> <%= @publication.species if @publication %> </td>
                            </tr>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <div class="column">
            <div class="card-content">
                <figure class="image">
                    <%= image_tag(@publication.image) if @publication %>
                </figure>
            </div>
        </div>
    </div>
    <br>
</div>

<h1 style="margin-left: 20px" class='is-size-2'>Comentarios</h1>
<br>

<% @comments.each do |comment| %>
    <% if comment.publication_id == @publication.id %>
        <article class="media" style="margin-left: 2%">
        <figure class="media-left">
            <p class="image is-64x64">
            <img src="https://bulma.io/images/placeholders/128x128.png">
            </p>
        </figure>
        <div class="media-content">
            <div class="content">
            <p>
                <strong><%= User.find_by(id: comment.user_id).name %></strong> <small>@<%= User.find_by(id: comment.user_id).user_name %></small>
                <br>
                <%= comment.description %>
            </p>
            </div>
            <nav class="level is-mobile">
            <div class="level-left">
                <% if current_user %>
                    <% if (current_user.id == comment.user_id) | (current_user.admin_role) %>
                        <a class="level-item">
                            <td><%= link_to 'Editar', comments_edit_path(comment.id) %></td>
                        </a>
                        <a class="level-item">
                            <td style="margin-left: 10px"><%= link_to 'Eliminar', comments_delete_path(comment.id), method: :delete if comment %></td>
                        </a>                   
                    <% end %>
                <% end %>
            </div>
            </nav>
        </div>
        </article>
    <% end %>
<% end %>

<button class="button is-rounded" style="margin-top: 20px; margin-left: 20px; margin-bottom: 30px"><%= link_to 'Volver', publications_index_path %></button>
<% if current_user %>
    <% if @publication.user_id != current_user.id%>
    <button class="button is-rounded" style="margin-top: 20px; margin-left: 20px; margin-bottom: 30px" data-tooltip="Enviar Solicitud"><%= link_to '¡Lo quiero!', requests_new_path(:don => @publication.user_id, :id_pb => @publication.id) %></button>
    <% end %>
    <button class="button is-rounded" style="margin-top: 20px; margin-left: 20px; margin-bottom: 30px"><%= link_to 'Comentar', comments_new_path(:id_pb => @publication.id) %></button>
    <% if (current_user.id == @publication.user_id) | (current_user.admin_role) %>
        <button class="button is-rounded" style="margin-top: 20px; margin-left: 20px; margin-bottom: 30px"><%= link_to 'Editar', publications_edit_path(@publication.id) if @publication %></button>
        <button class="button is-rounded" style="margin-top: 20px; margin-left: 20px; margin-bottom: 30px"><%= link_to 'Eliminar', publications_delete_path(@publication.id), method: :delete if @publication %></button>
    <% end %>
<% end %>