config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'welcome/index', to: 'welcome#index', as: 'welcome_index'
  root 'welcome#index'

  get 'publications/search', to: 'publications#search', as: 'publications_search', format: :html
  # para cuando este listo
  # root :to 'publications#index'
  # resources :publications (?)

  ############################################################################

  # CREATE
  get 'publications/new', to: 'publications#new', as: 'publications_new'
  post 'publications', to: 'publications#create'

  get 'reviews/new', to: 'reviews#new', as: 'reviews_new'
  post 'reviews', to: 'reviews#create'

  get 'chats/new', to: 'chats#new', as: 'chats_new'
  post 'chats', to: 'chats#create'

  get 'comments/new', to: 'comments#new', as: 'comments_new'
  post 'comments', to: 'comments#create'

  get 'requests/new', to: 'requests#new', as: 'requests_new'
  post 'requests', to: 'requests#create'

  get 'messages/new', to: 'messages#new', as: 'messages_new'
  post 'messages', to: 'messages#create'
  ############################################################################

  # READ
  get 'publications/index', to: 'publications#index', as: 'publications_index'
  get 'publications/:id', to: 'publications#show', as: 'publications_show'

  get 'reviews/index', to: 'reviews#index', as: 'reviews_index'
  get 'reviews/:id', to: 'reviews#show', as: 'reviews_show'

  get 'chats/index', to: 'chats#index', as: 'chats_index'
  get 'chats/:id', to: 'chats#show', as: 'chats_show'

  get 'comments/index', to: 'comments#index', as: 'comments_index'
  get 'comments/:id', to: 'comments#show', as: 'comments_show'

  get 'requests/index', to: 'requests#index', as: 'requests_index'
  get 'requests/:id', to: 'requests#show', as: 'requests_show'

  get 'messages/index', to: 'messages#index', as: 'messages_index'
  get 'messages/:id', to: 'messages#show', as: 'messages_show'

  # get 'users/:id', to: 'users#show', as: 'users_show'

  ############################################################################

  # UPDATE
  get 'publications/:id/edit', to: 'publications#edit', as: 'publications_edit'
  patch 'publications/:id', to: 'publications#update', as: 'publications_update'

  get 'reviews/:id/edit', to: 'reviews#edit', as: 'reviews_edit'
  patch 'reviews/:id', to: 'reviews#update', as: 'reviews_update'

  get 'chats/:id/edit', to: 'chats#edit', as: 'chats_edit'
  patch 'chats/:id', to: 'chats#update', as: 'chats_update'

  get 'comments/:id/edit', to: 'comments#edit', as: 'comments_edit'
  patch 'comments/:id', to: 'comments#update', as: 'comments_update'

  get 'requests/:id/edit', to: 'requests#edit', as: 'requests_edit'
  patch 'requests/:id', to: 'requests#update', as: 'requests_update'

  get 'messages/:id/edit', to: 'messages#edit', as: 'messages_edit'
  patch 'messages/:id', to: 'messages#update', as: 'messages_update'

  ############################################################################

  # DELETE
  delete 'publications/:id', to: 'publications#delete', as: 'publications_delete'

  delete 'reviews/:id', to: 'reviews#delete', as: 'reviews_delete'

  delete 'chats/:id', to: 'chats#delete', as: 'chats_delete'

  delete 'comments/:id', to: 'comments#delete', as: 'comments_delete'

  delete 'requests/:id', to: 'requests#delete', as: 'requests_delete'

  delete 'messages/:id', to: 'messages#delete', as: 'messages_delete'
  ############################################################################

  # DEVISE
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' },
                     path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :users, only: [:show]
  delete 'users/:id', to: 'users#destroy', as: 'admin_destroy_user'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/request.rb
# frozen_string_literal: true

class Request < ApplicationRecord
  validates :donator_id, :adoptant_id, :state, :publication_id,
            presence: { message: 'Debes completar todas las casillas requeridas' }
  validates :adoptant_id, numericality: { only_integer: true, message: 'El valor debe ser numérico' }
  validates :donator_id, numericality: { only_integer: true, message: 'El valor debe ser numérico' }

  belongs_to :adoptant, class_name: 'User', dependent: :destroy, inverse_of: false
  belongs_to :donator, class_name: 'User', dependent: :destroy, inverse_of: false

  belongs_to :publication
end

app/controllers/requests_controller.rb
# frozen_string_literal: true

class RequestsController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]
  def new
    @request = Request.new
  end

  def create
    @requests_params = params.require(:request).permit(:donator_id, :adoptant_id, :state, :publication_id)
    @request = Request.create(@requests_params)
    if @request.save
      redirect_to requests_index_path, notice: 'La solicitud ha sido creada correctamente'
    else
      render :new
    end
  end

  def index
    @requests = Request.all
  end

  def show
    @request = Request.find_by(id: params[:id])
  end

  def edit
    @request = Request.find_by(id: params[:id])
  end

  def update
    @request = Request.find_by(id: params[:id])
    @requests_params = params.require(:request).permit(:donator_id, :adoptant_id, :state, :publication_id)

    if @request.update(@requests_params)
      redirect_to requests_index_path, notice: 'La solicitud ha sido editada correctamente'
    else
      render :edit
    end
  end

  def delete
    @request = Request.find_by(id: params[:id])
    @request.destroy
    redirect_to requests_index_path, notice: 'La solicitud ha sido eliminada'
  end
end

app/helpers/requests_helper.rb
# frozen_string_literal: true

module RequestsHelper
end

app/views/requests/edit.html.erb
<br>
<h1 class='is-size-2' style="margin-left:20px">Editar solicitud</h1>
<br>
<br>

<div style="margin-left:20px">
<%= form_with(model: @request, method: :patch, url: requests_update_path, local: true) do |form| %>
    <%- if @request.errors.any? %>
        <div class="notification is-danger" style="width: 30%">
            Algo ha salido mal!
        </div>
    <% end %>
    <div class="field">
        <label class="label is-size-4 has-text-weight-light">Compra/Adopción</label>
        <div class="control" style="padding-right: 70%">
            <div class="select">
                <%= form.select(:kind, options_for_select([["Adopción", "Adopción"],["Venta", "Venta"]])) %>
            </div>
        </div>
    </div>
    <%- if @request.errors[:kind].any?%>
    <div class= "help is-danger">
        <%= @request.errors[:kind].first %>
    </div>
    <% end %>
    <br>
    <div class="field">
        <label class="label is-size-4 has-text-weight-light">Donante</label>
        <div class="control" style="padding-right: 70%">
            <%= form.text_field :donator, class: "input" %>
        </div>
    </div>
    <%- if @request.errors[:donator].any?%>
    <div class= "help is-danger">
        <%= @request.errors[:donator].first %>
    </div>
    <% end %>
    <br>
    <div class="field">
        <label class="label is-size-4 has-text-weight-light">Adoptante</label>
        <div class="control" style="padding-right: 70%">
            <%= form.text_field :user_id, class: "input" %>
        </div>
    </div>
    <%- if @request.errors[:user_id].any?%>
    <div class= "help is-danger">
        <%= @request.errors[:user_id].first %>
    </div>
    <% end %>
    <br>
    <div class="field">
        <label class="label is-size-4 has-text-weight-light">Estado</label>
        <div class="control" style="padding-right: 70%">
            <%= form.text_field :state, class: "input" %>
        </div>
    </div>
    <%- if @request.errors[:state].any?%>
    <div class= "help is-danger">
        <%= @request.errors[:state].first %>
    </div>
    <% end %>
    <br>
    <div class="control">
        <div class="action">
            <%= form.submit "Guardar", class: "button is-link" %>
        </div>
    </div>
<% end %>
</div>

<button class="button is-rounded" style="margin-top: 20px; margin-left: 20px; margin-bottom: 30px"><%= link_to 'Volver',requests_show_path(@request.id) if @request %></button>
<button class="button is-rounded" style="margin-top: 20px; margin-left: 20px; margin-bottom: 30px"><%= link_to 'Listado de solicitudes', requests_index_path %></button>

app/views/requests/index.html.erb
<div class="row">
    <div class="column">
    <div class="content">
    <h2>Solicitudes Enviadas</h2>
    </div>
        <table class="table is-bordered is-striped is-narrow is-hoverable is-fullwidth" style="width: 40%">
            <thead>
                <tr style= "background-color: #FF7F50">
                    <th style= "color: white; text-align: center;">Nombre Donante</th>
                    <th style= "color: white; text-align: center;">Estado</th>
                </tr>
            </thead>

            <tbody>
                <% @requests.each do |req|%>
                    <% if current_user.id == req.adoptant.id%>

                        <tr>
                            <td style="text-align: center;"><%= User.find_by(id: req.donator).user_name.capitalize %></td>
                            <td style="text-align: center;"><%= req.state.capitalize %></td>
                        </tr>
                    <% end %>
                <% end %>
            </tbody>
        </table>
    </div>
    <div class="column">
    <div class="content">
    <h2>Solicitudes recibidas</h2>
    </div>
        <table class="table is-bordered is-striped is-narrow is-hoverable is-fullwidth" style="width: 40%">
            <thead>
                <tr style= "background-color: #FF7F50">
                    <th style= "color: white; text-align: center;">Nombre Adoptante</th>
                    <th style= "color: white; text-align: center;">Estado</th>
                </tr>
            </thead>

            <tbody>
                <% @requests.each do |req|%>
                    <% if current_user.id == req.donator.id%>
                        <tr>

                            <td style="text-align: center;vertical-align: middle;"><%= User.find_by(id: req.adoptant).user_name.capitalize %></td>
                            <td style="text-align: center;vertical-align: middle;"><%= req.state.capitalize %></td>
                            <td style="text-align: center;vertical-align: middle;"><button class="button is-success"><%= link_to 'Aceptar', chats_new_path(:don => req.donator.id, :adp => req.adoptant.id) %></button></td>
                            <td style="text-align: center;vertical-align: middle;"><button class="button is-danger">Cancelar</button></td>
                        </tr>
                    <% end %>
                <% end %>
            </tbody>
        </table>
    </div>
</div>

<button class="button is-rounded" style="margin-top: 20px; margin-left: 20px; margin-bottom: 30px"><%= link_to 'Volver', :back %></button>

<!-- 
<button class="button is-rounded" style="margin-top: 20px; margin-left: 20px; margin-bottom: 30px"><%= link_to 'Editar', requests_edit_path(@request.id) if @request %></button>
<button class="button is-rounded" style="margin-top: 20px; margin-left: 20px; margin-bottom: 30px"><%= link_to 'Eliminar', requests_delete_path(@request.id), method: :delete if @request %></button>

<button class="button is-rounded" style="margin-top: 20px; margin-left: 20px"><%= link_to 'Crear nueva solicitud', requests_new_path %></button>
-->

app/views/requests/new.html.erb
<br>
<h1 class='is-size-2' style="margin-left:20px">Nueva solicitud</h1>
<br>
<br>

<div style="margin-left:20px">
<%= form_with(model: @request, method: :post, local: true) do |form| %>
    <%- if @request.errors.any? %>
    <%= @request.errors.full_messages%>
        <div class="notification is-danger" style="width: 30%">
            Algo ha salido mal!
        </div>
    <% end %>
    <br>
        <div class="field">
        <div class="control" style="padding-right: 70%">
            <%= form.text_field :donator_id, value: params[:don].to_i, class: "input", type: :hidden %>
        </div>
    </div>
    <%- if @request.errors[:donator_id].any?%>
    <div class= "help is-danger">
        <%= @request.errors[:donator_id].first %>
    </div>
    <% end %>
    <br>
    <div class="field">
        <div class="control" style="padding-right: 70%">
            <%= form.text_field :adoptant_id, value: current_user.id, class: "input", type: :hidden %>
        </div>
    </div>
    <%- if @request.errors[:adoptant_id].any?%>
    <div class= "help is-danger">
        <%= @request.errors[:adoptant_id].first %>
    </div>
    <% end %>
    <br>
    <div class="field">
        <div class="control" style="padding-right: 70%">
            <%= form.text_field :state, value: 'pendiente', class: "input", type: :hidden %>
        </div>
    </div>
    <%- if @request.errors[:state].any?%>
    <div class= "help is-danger">
        <%= @request.errors[:state].first %>
    </div>
    <% end %>
    <br>
    <div class="field">
        <div class="control" style="padding-right: 70%">
            <%= form.text_field :publication_id, value: params[:id_pb].to_i, class: "input", type: :hidden %>
        </div>
    </div>
    <%- if @request.errors[:publication_id].any?%>
    <div class= "help is-danger">
        <%= @request.errors[:publication_id].first %>
    </div>
    <% end %>
    <br>
    <div class="control">
        <div class="action">
            <%= form.submit "Crear Solicitud", class: "button is-link" %>
            <% # link_to 'crear chat (test)', chats_new_path(donat: @request.donator, adopt: @request.adoptant) %>
            <% # no funciono%>
        </div>
    </div>
<% end %>
</div>

app/views/requests/show.html.erb
<div class="row">
    <div class="column">
    <h2>Solicitudes Enviadas</h2>
        <table class="table is-striped">
            <thead>
                <tr>
                    <th>Nombre Donante</th>
                    <th>Estado</th>
                </tr>
            </thead>

            <tbody>
                <tr>
                    <td><%= User.find_by(id:@request.donator).user_name if current_user.id == User.find_by(id: @request.adoptant).id %></td>
                    <td><%= @request.state if @request %></td>
                </tr>
            </tbody>
        </table>
    </div>
    <div class="column">
    <h2>Solicitudes recibidas</h2>
        <table class="table is-striped">
            <thead>
                <tr>
                    <th>Nombre Adoptante</th>
                    <th>Estado</th>
                </tr>
            </thead>

            <tbody>
                <tr>
                    <td><%= User.find_by(id:@request.adoptant).user_name if current_user.id == User.find_by(id: @request.donator).id %></td>
                    <td><%= @request.state if @request %></td><button>Aceptar</button><button>Cancelar</button>
                </tr>
            </tbody>
        </table>
    </div>
</div>
<button class="button is-rounded" style="margin-top: 20px; margin-left: 20px; margin-bottom: 30px"><%= link_to 'Volver', requests_index_path %></button>
<button class="button is-rounded" style="margin-top: 20px; margin-left: 20px; margin-bottom: 30px"><%= link_to 'Editar', requests_edit_path(@request.id) if @request %></button>
<button class="button is-rounded" style="margin-top: 20px; margin-left: 20px; margin-bottom: 30px"><%= link_to 'Eliminar', requests_delete_path(@request.id), method: :delete if @request %></button>