config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'welcome/index', to: 'welcome#index', as: 'welcome_index'
  root 'welcome#index'

  get 'publications/search', to: 'publications#search', as: 'publications_search', format: :html
  # para cuando este listo
  # root :to 'publications#index'
  # resources :publications (?)

  ############################################################################

  # CREATE
  get 'publications/new', to: 'publications#new', as: 'publications_new'
  post 'publications', to: 'publications#create'

  get 'reviews/new', to: 'reviews#new', as: 'reviews_new'
  post 'reviews', to: 'reviews#create'

  get 'chats/new', to: 'chats#new', as: 'chats_new'
  post 'chats', to: 'chats#create'

  get 'comments/new', to: 'comments#new', as: 'comments_new'
  post 'comments', to: 'comments#create'

  get 'requests/new', to: 'requests#new', as: 'requests_new'
  post 'requests', to: 'requests#create'

  get 'messages/new', to: 'messages#new', as: 'messages_new'
  post 'messages', to: 'messages#create'
  ############################################################################

  # READ
  get 'publications/index', to: 'publications#index', as: 'publications_index'
  get 'publications/:id', to: 'publications#show', as: 'publications_show'

  get 'reviews/index', to: 'reviews#index', as: 'reviews_index'
  get 'reviews/:id', to: 'reviews#show', as: 'reviews_show'

  get 'chats/index', to: 'chats#index', as: 'chats_index'
  get 'chats/:id', to: 'chats#show', as: 'chats_show'

  get 'comments/index', to: 'comments#index', as: 'comments_index'
  get 'comments/:id', to: 'comments#show', as: 'comments_show'

  get 'requests/index', to: 'requests#index', as: 'requests_index'
  get 'requests/:id', to: 'requests#show', as: 'requests_show'

  get 'messages/index', to: 'messages#index', as: 'messages_index'
  get 'messages/:id', to: 'messages#show', as: 'messages_show'

  # get 'users/:id', to: 'users#show', as: 'users_show'

  ############################################################################

  # UPDATE
  get 'publications/:id/edit', to: 'publications#edit', as: 'publications_edit'
  patch 'publications/:id', to: 'publications#update', as: 'publications_update'

  get 'reviews/:id/edit', to: 'reviews#edit', as: 'reviews_edit'
  patch 'reviews/:id', to: 'reviews#update', as: 'reviews_update'

  get 'chats/:id/edit', to: 'chats#edit', as: 'chats_edit'
  patch 'chats/:id', to: 'chats#update', as: 'chats_update'

  get 'comments/:id/edit', to: 'comments#edit', as: 'comments_edit'
  patch 'comments/:id', to: 'comments#update', as: 'comments_update'

  get 'requests/:id/edit', to: 'requests#edit', as: 'requests_edit'
  patch 'requests/:id', to: 'requests#update', as: 'requests_update'

  get 'messages/:id/edit', to: 'messages#edit', as: 'messages_edit'
  patch 'messages/:id', to: 'messages#update', as: 'messages_update'

  ############################################################################

  # DELETE
  delete 'publications/:id', to: 'publications#delete', as: 'publications_delete'

  delete 'reviews/:id', to: 'reviews#delete', as: 'reviews_delete'

  delete 'chats/:id', to: 'chats#delete', as: 'chats_delete'

  delete 'comments/:id', to: 'comments#delete', as: 'comments_delete'

  delete 'requests/:id', to: 'requests#delete', as: 'requests_delete'

  delete 'messages/:id', to: 'messages#delete', as: 'messages_delete'
  ############################################################################

  # DEVISE
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' },
                     path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :users, only: [:show]
  delete 'users/:id', to: 'users#destroy', as: 'admin_destroy_user'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/chat.rb
# frozen_string_literal: true

class Chat < ApplicationRecord
  validates :adoptant_id, :donator_id, presence: { message: 'Debes completar todas las casillas' }
  validates :adoptant_id, :donator_id, numericality: { only_integer: true, message: 'El valor debe ser numérico' }

  belongs_to :adoptant, class_name: 'User', dependent: :destroy, inverse_of: false
  belongs_to :donator, class_name: 'User', dependent: :destroy, inverse_of: false
  has_many :messages
end

app/controllers/chats_controller.rb
# frozen_string_literal: true

class ChatsController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]
  def index
    @chats = Chat.all
  end

  def show
    @chat = Chat.find_by(id: params[:id])
  end

  def new
    @chat = Chat.new
  end

  def create
    @chats_params = params.require(:chat).permit(:adoptant_id, :donator_id)
    @chat = Chat.create(@chats_params)
    if @chat.save
      redirect_to chats_index_path, notice: 'Chat creado'
    else
      render :new
    end
  end

  def edit
    @chat = Chat.find_by(id: params[:id])
  end

  def update
    @chat = Chat.find_by(id: params[:id])
    @chats_params = params.require(:chat).permit(:adoptant_id, :donator_id)

    if @chat.update(@chats_params)
      redirect_to chats_index_path, notice: 'Chat editado correctamente'
    else
      render :edit
    end
  end

  def delete
    @chat = Chat.find_by(id: params[:id])
    @chat.destroy
    redirect_to chats_index_path, notice: 'chat eliminado correctamente'
  end
end

app/helpers/chats_helper.rb
# frozen_string_literal: true

module ChatsHelper
end

app/views/chats/edit.html.erb
<br>
<h1 class='is-size-2' style="margin-left:20px">Editar chat</h1>
<br>
<p>Recuerda, solo puedes editar el chat completo, no un mensaje particular</p>
<br>
<div style="margin-left:20px">
<%= form_with(model: @chat, method: :patch, url: chats_update_path, local: true) do |form| %>
    <%- if @chat.errors.any? %>
        <div class="notification is-danger" style="width: 30%">
            Algo ha salido mal!
        </div>
    <% end %>
    <div class="field">
        <label class="label is-size-4 has-text-weight-light">Identificador Chat</label>
        <div class="control" style="padding-right: 70%">
            <%= form.text_field :donator, class: "input" %>
        </div>
    </div>
    <%- if @chat.errors[:donator].any?%>
        <div class= "help is-danger">
            <%= @chat.errors[:donator].first %>
        </div>
    <% end %>
    <br>
        <div class="field">
        <label class="label is-size-4 has-text-weight-light">Contenido Chat</label>
        <div class="control" style="padding-right: 70%">
            <%= form.text_field :chat, class: "input" %>
        </div>
    </div>
    <%- if @chat.errors[:chat].any?%>
        <div class= "help is-danger">
            <%= @chat.errors[:chat].first %>
        </div>
    <% end %>
    <br>

    <div class="control">
        <div class="action">
            <%= form.submit "Guardar", class: "button is-link" %>
        </div>
    </div>
<% end %>
</div>
<button class="button is-rounded" style="margin-top: 20px; margin-left: 20px; margin-bottom: 30px"><%= link_to 'Volver',chats_show_path(@chat.id) if @chat %></button>
<button class="button is-rounded" style="margin-top: 20px; margin-left: 20px; margin-bottom: 30px"><%= link_to 'Otros chats', chats_index_path %></button>

app/views/chats/index.html.erb
<br>
<h1 style="margin-left: 20px" class='is-size-2'>Mis Chats</h1>
<p style="margin-top: 20px; margin-bottom:20px; margin-left: 20px">Porque quien no querría que todos los chats de todas las personas fueran publicos</p>

<% if notice %>
    <div class="notification is-success" style= "width:30%; margin-left: 1%">
        <%= notice %>
    </div>
<% end %>

<div class="container">
    <table class="table">
        <thead>
            <tr>
                <th>Contactos</th>
            </tr>
        </thead>

        <tbody>

            <% @chats.each do |chat|%>
                <% if (current_user.id == chat.donator.id) | (current_user.id == chat.adoptant.id)%>
                    <tr>
                        <td><%= User.find_by(id: chat.adoptant).user_name if current_user.id == chat.donator.id %></td>
                        <td><%= User.find_by(id: chat.donator).user_name if current_user.id == chat.adoptant.id %></td>
                        <td><%= link_to 'Ver detalle', chats_show_path(chat.id) %></td>
                    </tr>
                <% end %>
            <% end %>
        </tbody>
    </table>
</div>

<!-- probablemente haya que sacar este boton despues-->
<button class="button is-rounded" style="margin-top: 20px; margin-left: 20px"><%= link_to 'Crear nuevo chat', chats_new_path %></button>
<thead>

app/views/chats/new.html.erb
<br>
<h1 class='is-size-2' style="margin-left:20px">Crea un nuevo chat</h1>
<br>
<br>
<div style="margin-left:20px">
<%= form_with(model: @chat, method: :post, local: true) do |form| %>
    <%- if @chat.errors.any? %>
    <%= @chat.errors.full_messages%>
        <div class="notification is-danger" style="width: 30%">
            Algo ha salido mal!
        </div>
    <% end %>
    <div class="field">
        <div class="control" style="padding-right: 70%">
            <%= form.text_field :donator_id, value: params[:don].to_i, class: "input", type: :hidden %>
        </div>
    </div>
    <%- if @chat.errors[:donator_id].any?%>
    <div class= "help is-danger">
        <%= @chat.errors[:donator_id].first %>
    </div>
    <% end %>
    <div class="field">
        <div class="control" style="padding-right: 70%">
            <%= form.text_field :adoptant_id, value: params[:adp].to_i, class: "input", type: :hidden %>
        </div>
    </div>
    <br>

    <div class="control">
        <div class="action">
            <%= form.submit "Crear Chat", class: "button is-link" %>
        </div>
    </div>
<% end %>
</div>

<button class="button is-rounded" style="margin-top: 20px; margin-left: 20px"><%= link_to 'Volver a la lista de chats', chats_index_path %></button>

app/views/chats/show.html.erb
<% if notice %>
    <div class="notification is-success" style= "width:30%; text-align: center;margin-left: 20px; margin-top: 1%">
        <%= notice %>
    </div>
<% end %>

<div style="margin-left: 1%; margin-right: 1%;border-color: black;border-style: solid;border-radius: 7px;; margin-bottom: 1%; width: 50%; margin-top: 1%">
    <div class="card">
        <header class="card-header" style="display:block;padding-top: 1%; background-color: lightblue">
            <p class="title" style="margin-left: 1%">
                <strong> <%= User.find_by(id: @chat.adoptant).name if current_user.id == User.find_by(id: @chat.donator).id %> </strong>
                <strong> <%= User.find_by(id: @chat.donator).name if current_user.id == User.find_by(id: @chat.adoptant).id %> </strong>
            </p>
        </header>
    </div>
</div>

<% Message.all.each do |message|%>
    <% if message.chat_id == @chat.id%>
        <% if (message.reciever.id == current_user.id) | (message.sender.id == current_user.id) %>
            <article class="media" style="margin-left: 2%">
            <figure class="media-left">
                <p class="image is-64x64">
                <img src="https://bulma.io/images/placeholders/128x128.png">
                </p>
            </figure>
            <div class="media-content">
                <div class="content">
                <p>
                    <strong><%= User.find_by(id: message.sender).name %></strong>
                    <br>
                    <%= message.content %>
                </p>
                </div>
                <nav class="level is-mobile">
                <div class="level-left">
                    <% if current_user %>
                        <% if (current_user.id == message.sender.id) | (current_user.admin_role) %>
                            <a class="level-item">
                                <td><%= link_to 'Editar', messages_edit_path(message.id) %></td>
                            </a>
                            <a class="level-item">
                                <td style="margin-left: 10px"><%= link_to 'Eliminar', messages_delete_path(message.id), method: :delete if message %></td>
                            </a>                   
                        <% end %>
                    <% end %>
                </div>
                </nav>
            </div>
            </article>
        <% end %>
    <% end %>
<% end %>
<% other = User.find_by(id: @chat.adoptant).id if current_user.id == User.find_by(id: @chat.donator).id %>
<% other = User.find_by(id: @chat.donator).id if current_user.id == User.find_by(id: @chat.adoptant).id %>
<button class="button is-rounded" style="margin-top: 20px; margin-left: 20px; margin-bottom: 30px"><%= link_to 'Enviar mensaje', messages_new_path(:send => current_user.id, :rec => other, :ch_id => @chat.id) %></button>
<!-- este ultimo boton de enviar mensaje no puede ser probado todavia pero creo que funciona -->
<button class="button is-rounded" style="margin-top: 20px; margin-left: 20px; margin-bottom: 30px"><%= link_to 'Volver', chats_index_path %></button>
<button class="button is-rounded" style="margin-top: 20px; margin-left: 20px; margin-bottom: 30px"><%= link_to 'Eliminar', chats_delete_path(@chat.id), method: :delete if @chat %></button>